public enum GameState {
		HeadingToFred,
		TalkingToFred,
		HeadingToFirstWoman,
		TalkingToFirstWoman,
		HeadingToBuyPizza,
		ObtainedPizza,
		TalkingToFirstWomanWithPizza,
        SlappedByFirstWomen,
		HeadingToSecondWoman,
		TalkingToSecondWoman,
        HeadingToGetChinese,
        ObtainedChinese,
        TalkingToSecondWomanWithChinese,
        SlappedBySecondWomen,
        HeadingToProstitute,
        TalkingToProstitute,
        HeadingToATM,
        ObtainedCash,
        TalkingToProstituteWithCash,
        KnockedOut,
        PoliceStation,
        FinalDate,
		NoChange,


}
